webAppHost: 'http://localhost:3000'

jwt:
  token: 'dev_auth_token'

mongoDb:
  uri: 'mongodb://localhost:27017/bubble-db-demo-dev'

grafana:
  labels:
    env: 'development'

public:
  env: 'development'
